name: Display version

on: [push, pull_request]

permissions:
    contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build "setuptools-git-versioning>=2,<3"
        pip install torch --index-url https://download.pytorch.org/whl/cpu
    - name: Display version
      run: |
          setuptools-git-versioning -v >> $GITHUB_STEP_SUMMARY